### ISSUE TITLE
add location for images taken in the app

### ISSUE THREAD

**Issue by ubahnverleih** [lyrk/Commons#23]
existing images from camera coll contains GPS location, but images taken in the app doesnt

**Comment by ubahnverleih** [comment]
added in c8e45ef65002e8f46429a4fd94b5e311cbc3a144
now the App asks for location permissions before shooting a photo. it takes the location in the moment tapping on "Use Photo"

**Comment by Ainali** [comment]
Why not taking the location when actually shooting the photo?

**Comment by ubahnverleih** [comment]
I've found no easy way to detect when the photo is taken. A way would be to collect the locations with timestamp and sync it later with the exif data of the image
I opend a new issue for it: https://github.com/lyrk/Commons/issues/28
