### ISSUE TITLE
US App Store Issue

### ISSUE THREAD

**Issue by AntiCompositeNumber** [lyrk/Commons#34]
When I try to download the app from the [App Store](https://itunes.apple.com/app/commons-reloaded/id962894692), I get the error:
### Item Not Available

The item you've requested is not currently available in the U.S. store.
![img_0638](https://cloud.githubusercontent.com/assets/10331574/17278727/b4625d8e-5731-11e6-9f28-92fe18c20917.PNG)

**Comment by nicolas-raoul** [comment]
Same here in Japan.

**Comment by thomersch** [comment]
Duplicate of #33
